# Generated by Django 6.0.5 on 2026-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='sources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='grade',
            field=models.IntegerField(default=6),
        ),
    ]
