# Generated by Django 6.0.5 on 2026-06-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_learner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='segment_count',
        ),
        migrations.AddField(
            model_name='session',
            name='chapter_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='setting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('paragraphs', models.JSONField()),
                ('summary', models.TextField(blank=True)),
                ('difficulty_at_time', models.IntegerField()),
                ('sources', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('concept', models.CharField(blank=True, max_length=100)),
                ('user_answer_index', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
