# Generated by Django 6.0.5 on 2026-06-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_session_segment_count_session_chapter_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('concept', models.CharField(max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_stats', to='core.learner')),
            ],
            options={
                'unique_together': {('learner', 'topic', 'concept')},
            },
        ),
    ]
