# Generated by Django 6.0.5 on 2026-06-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_conceptstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='content_level',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
