# Generated by Django 6.0.5 on 2026-08-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_session_content_level_session_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fallback_served', 'Canned chapter served instead of a generated one'), ('retry_succeeded', 'Retry produced a textbook-grounded chapter'), ('retry_failed', 'Retry fell back again; the original chapter was kept')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_events', to='core.chapter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_events', to='core.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
